### PR TITLE
country_data_pop

### PR DESCRIPTION
**Pull request by karenjh2**

### CODE REVIEW

**Comment by npaterno** [comment]
@karenjh2 

For this data set, it might be better to limit to every 5 years and add the gdp for each year. If that data is unavailable or hard to obtain, we can change this to be just a population dataset.

**Comment by karenjh2** [comment]
Hi Nick,

 

I do not see historic GDP. I have sent a request to the World Bank help desk for that data. I will get back to you when I receive a reply.

 

One cannot simply take a years GDP and divide it by that years population to obtain GDP per capita because it is not comparable to current GDP. It is not in today’s dollars. To do that, we would also need to add a factor to convert that year’s GDP to 2020 dollars.

 

So I am thinking that I should remove GDP from the data set and create a separate data set for GDP when I obtain the historic data.

 

 

Karen Higgins

**Comment by npaterno** [comment]
That should work. Then for the examples, we could add a time-series graph for a few select countries.

**Comment by karenjh2** [comment]
To create a graph, I used reshape2 to change the data. That caused error in devtools::check()

 

 



 

 

Is reshape2 something that you need to add?

 

Karen Higgins

**Comment by npaterno** [comment]
Hi Karen,

Is there a way to make the graph without that package?; since our data
needs to be able to merge into the openintro package we can only use
packages that are either imported or suggested by the openintro package (
link <https://github.com/OpenIntroStat/openintro/blob/master/DESCRIPTION>).
I could add reshape2 to our package but then the data won't merge to
openintro.

Best,
~N

**Comment by npaterno** [comment]
moved to pr #14

**Pull request closed without merging**
